# Introducao a arquivos notebooks 

Este arquivo e um bloco markdown para testes

In [4]:
print('Hello, World!')
# Este e um exemplo de celula de codigo Python em um notebook Jupyter.

Hello, World!

In [5]:
numero = 10
numero2 = 5
soma = numero + numero2
print(f"A soma de {numero} e {numero2} e igual a {soma}.")

A soma de 10 e 5 e igual a 15.

In [8]:
# Instalando biblioteca pandas

! pip install pandas -q

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
# importando pandas para analise 

import pandas as pd

# lendo dataset (arquivo com os dados)

df = pd.read_csv('../dados/dados_alunos.csv')

In [6]:
df

        nome  idade genero        curso  semestre  nota_final  faltas
0   Fernanda     22      F   Engenharia         7        8.85      21
1    Eduardo     28      M          ADS         1        6.49       9
2       Igor     24      M  Arquitetura         3        5.85       8
3       Igor     29      F  Arquitetura        10        5.65       7
4      Bruno     28      M  Arquitetura         7        8.64       5
..       ...    ...    ...          ...       ...         ...     ...
95    Helena     26      M          ADS         2        6.65      21
96    Carlos     20      F   Engenharia         8        9.33      24
97     Diana     27      M      Direito         1        9.31      17
98      Igor     27      F     Medicina         9        8.88      17
99    Carlos     22      F     Medicina         8        9.75      21

[100 rows x 7 columns]

In [7]:
#visualizando o inicio do dataset
df.head()

       nome  idade genero        curso  semestre  nota_final  faltas
0  Fernanda     22      F   Engenharia         7        8.85      21
1   Eduardo     28      M          ADS         1        6.49       9
2      Igor     24      M  Arquitetura         3        5.85       8
3      Igor     29      F  Arquitetura        10        5.65       7
4     Bruno     28      M  Arquitetura         7        8.64       5

In [10]:
df.tail()

      nome  idade genero       curso  semestre  nota_final  faltas
95  Helena     26      M         ADS         2        6.65      21
96  Carlos     20      F  Engenharia         8        9.33      24
97   Diana     27      M     Direito         1        9.31      17
98    Igor     27      F    Medicina         9        8.88      17
99  Carlos     22      F    Medicina         8        9.75      21

In [11]:
df.shape

(100, 7)

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   nome        100 non-null    str
 1   idade       100 non-null    int64
 2   genero      100 non-null    str
 3   curso       100 non-null    str
 4   semestre    100 non-null    int64
 5   nota_final  100 non-null    float64
 6   faltas      100 non-null    int64
dtypes: float64(1), int64(3), str(3)
memory usage: 5.6 KB