# Tratamento de valores duplicados com Python e Pandas

## 1. Importar as bibliotecas

Usaremos o **Pandas**, biblioteca bastante comum para manipulação e análise de dados. O `display()` ajuda a visualizar tabelas no Jupyter Notebook.

In [9]:
import pandas as pd
from IPython.display import display

pd.set_option("display.max_rows", 60)
pd.set_option("display.max_columns", None)

## 2. Carregar o arquivo de dados

Coloque o arquivo `dados_duplicados.csv` na mesma pasta deste notebook. Se necessário, ajuste o caminho no `read_csv()`.

In [10]:


df = pd.read_csv("../dados/dados_duplicados.csv")

print(f"Quantidade de linhas: {len(df)}")
print(f"Quantidade de colunas: {len(df.columns)}")
display(df.head(10))

Quantidade de linhas: 43
Quantidade de colunas: 6

   id_aluno             nome  idade           curso  nota      cidade
0       101        Ana Souza     20             ADS   8.5    Brasília
1       102      Carlos Lima     22             ADS   7.0     Goiânia
2       103    Beatriz Alves     21           Redes   9.2    Brasília
3       101        Ana Souza     20             ADS   8.5    Brasília
4       104      Diego Rocha     23             ADS   6.8    Anápolis
5       102      Carlos Lima     22             ADS   7.0     Goiânia
6       105        Ana Souza     20             ADS   9.0    Brasília
7       106   Fernanda Costa     24  Banco de Dados   8.0    Brasília
8       103    Beatriz Alves     21           Redes   9.2    Brasília
9       107  Gabriel Martins     20             ADS   7.5  Taguatinga

## 3. O que é uma duplicata?

Uma linha duplicada é um registro que repete outro segundo os campos usados na comparação. Com `df.duplicated()`, o Pandas compara a linha com as linhas anteriores e marca como `True` as ocorrências repetidas.

Por padrão, a primeira ocorrência é marcada como `False` e as seguintes como `True`.

In [11]:
df.duplicated()

0     False
1     False
2     False
3      True
4     False
5      True
6     False
7     False
8      True
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
dtype: bool

## 4. Contar duplicatas completas

O método `sum()` soma os valores `True`, permitindo contar quantas linhas duplicadas existem.

In [12]:
quantidade_duplicadas = df.duplicated().sum()
print(f"Duplicatas completas encontradas: {quantidade_duplicadas}")

Duplicatas completas encontradas: 3

## 5. Visualizar todas as linhas envolvidas em duplicações

Com `keep=False`, todas as ocorrências de um grupo duplicado são marcadas, inclusive a primeira. Isso ajuda a investigar antes de decidir o que remover.

In [13]:
duplicatas = df[df.duplicated(keep=False)].sort_values(by=["id_aluno"])
display(duplicatas)

   id_aluno           nome  idade  curso  nota    cidade
0       101      Ana Souza     20    ADS   8.5  Brasília
3       101      Ana Souza     20    ADS   8.5  Brasília
1       102    Carlos Lima     22    ADS   7.0   Goiânia
5       102    Carlos Lima     22    ADS   7.0   Goiânia
2       103  Beatriz Alves     21  Redes   9.2  Brasília
8       103  Beatriz Alves     21  Redes   9.2  Brasília

## 6. Remover linhas completamente duplicadas

`drop_duplicates()` retorna um DataFrame sem as linhas completamente duplicadas. Por padrão, mantém a primeira ocorrência. Aqui, guardamos o resultado em uma nova variável para preservar `df` original para comparação.

In [14]:
df_sem_duplicatas = df.drop_duplicates()

print("Linhas antes:", len(df))
print("Linhas depois:", len(df_sem_duplicatas))
print("Duplicatas restantes:", df_sem_duplicatas.duplicated().sum())

display(df_sem_duplicatas.head())

Linhas antes: 43
Linhas depois: 40
Duplicatas restantes: 0

   id_aluno           nome  idade  curso  nota    cidade
0       101      Ana Souza     20    ADS   8.5  Brasília
1       102    Carlos Lima     22    ADS   7.0   Goiânia
2       103  Beatriz Alves     21  Redes   9.2  Brasília
4       104    Diego Rocha     23    ADS   6.8  Anápolis
6       105      Ana Souza     20    ADS   9.0  Brasília

## 7. Entender o parâmetro `keep`

- `keep="first"`: mantém a primeira ocorrência (padrão).
- `keep="last"`: mantém a última ocorrência.
- `keep=False`: remove todas as ocorrências que fazem parte de um grupo duplicado.

Faça testes nas células abaixo para comparar os resultados.

In [15]:
# Mantém a primeira ocorrência
df.drop_duplicates(keep="first").head(10)

    id_aluno             nome  idade           curso  nota      cidade
0        101        Ana Souza     20             ADS   8.5    Brasília
1        102      Carlos Lima     22             ADS   7.0     Goiânia
2        103    Beatriz Alves     21           Redes   9.2    Brasília
4        104      Diego Rocha     23             ADS   6.8    Anápolis
6        105        Ana Souza     20             ADS   9.0    Brasília
7        106   Fernanda Costa     24  Banco de Dados   8.0    Brasília
9        107  Gabriel Martins     20             ADS   7.5  Taguatinga
10       108    Mariana Silva     22           Redes   8.7    Brasília
11       109     Pedro Santos     21             ADS   6.5        Gama
12       110   Lucas Ferreira     23  Banco de Dados   7.8    Brasília

In [16]:
# Mantém a última ocorrência
df.drop_duplicates(keep="last").head(10)

    id_aluno             nome  idade           curso  nota      cidade
3        101        Ana Souza     20             ADS   8.5    Brasília
4        104      Diego Rocha     23             ADS   6.8    Anápolis
5        102      Carlos Lima     22             ADS   7.0     Goiânia
6        105        Ana Souza     20             ADS   9.0    Brasília
7        106   Fernanda Costa     24  Banco de Dados   8.0    Brasília
8        103    Beatriz Alves     21           Redes   9.2    Brasília
9        107  Gabriel Martins     20             ADS   7.5  Taguatinga
10       108    Mariana Silva     22           Redes   8.7    Brasília
11       109     Pedro Santos     21             ADS   6.5        Gama
12       110   Lucas Ferreira     23  Banco de Dados   7.8    Brasília

In [17]:
# Remove todas as linhas que fazem parte de grupos duplicados
df.drop_duplicates(keep=False).head(10)

    id_aluno             nome  idade           curso  nota      cidade
4        104      Diego Rocha     23             ADS   6.8    Anápolis
6        105        Ana Souza     20             ADS   9.0    Brasília
7        106   Fernanda Costa     24  Banco de Dados   8.0    Brasília
9        107  Gabriel Martins     20             ADS   7.5  Taguatinga
10       108    Mariana Silva     22           Redes   8.7    Brasília
11       109     Pedro Santos     21             ADS   6.5        Gama
12       110   Lucas Ferreira     23  Banco de Dados   7.8    Brasília
13       111   Juliana Mendes     20             ADS   9.1     Goiânia
14       112  Rafael Oliveira     24           Redes   7.2    Brasília
15       113   Camila Ribeiro     22             ADS   8.3    Anápolis

## 8. Procurar duplicatas em colunas específicas

Às vezes, queremos verificar repetição por uma chave, como `id_aluno`, em vez de comparar a linha inteira.

- `duplicated(subset=["id_aluno"])` identifica IDs repetidos.
- `drop_duplicates(subset=["id_aluno"], keep="last")` mantém o último registro de cada ID.

**Importante:** escolha `subset` de acordo com a regra do problema. Não use o nome como chave única se pessoas diferentes puderem ter o mesmo nome.

In [18]:
duplicatas_por_id = df[df.duplicated(subset=["id_aluno"], keep=False)].sort_values("id_aluno")
display(duplicatas_por_id)

   id_aluno           nome  idade  curso  nota    cidade
0       101      Ana Souza     20    ADS   8.5  Brasília
3       101      Ana Souza     20    ADS   8.5  Brasília
1       102    Carlos Lima     22    ADS   7.0   Goiânia
5       102    Carlos Lima     22    ADS   7.0   Goiânia
2       103  Beatriz Alves     21  Redes   9.2  Brasília
8       103  Beatriz Alves     21  Redes   9.2  Brasília

In [19]:
df_um_registro_por_id = df.drop_duplicates(subset=["id_aluno"], keep="last")

print("Linhas originais:", len(df))
print("Linhas após manter um registro por ID:", len(df_um_registro_por_id))

Linhas originais: 43
Linhas após manter um registro por ID: 40

## 9. Mesmo nome não significa necessariamente duplicata

Neste conjunto, Ana Souza aparece em registros diferentes com notas diferentes. São linhas diferentes; se removermos apenas pelo nome, poderemos apagar uma informação legítima.

A célula a seguir mostra esse caso.

In [20]:
display(df[df["nome"] == "Ana Souza"])

   id_aluno       nome  idade curso  nota    cidade
0       101  Ana Souza     20   ADS   8.5  Brasília
3       101  Ana Souza     20   ADS   8.5  Brasília
6       105  Ana Souza     20   ADS   9.0  Brasília

In [21]:
# Demonstração: manter somente a última linha por nome.
# Use apenas se essa for realmente a regra de negócio!
df_exemplo_por_nome = df.drop_duplicates(subset=["nome"], keep="last")
display(df_exemplo_por_nome[df_exemplo_por_nome["nome"] == "Ana Souza"])

   id_aluno       nome  idade curso  nota    cidade
6       105  Ana Souza     20   ADS   9.0  Brasília

## 10. Contar frequências de valores

`value_counts()` conta quantas vezes cada valor aparece em uma coluna. Ele é útil para encontrar valores repetidos, mas não remove linhas.

In [22]:
print(df["nome"].value_counts().head(10))

nome
Ana Souza          3
Carlos Lima        2
Beatriz Alves      2
Diego Rocha        1
Fernanda Costa     1
Gabriel Martins    1
Mariana Silva      1
Pedro Santos       1
Lucas Ferreira     1
Juliana Mendes     1
Name: count, dtype: int64

## 11. Validar o resultado e salvar

Depois do tratamento, confira se ainda existem duplicatas segundo a regra escolhida. Salve em um arquivo novo para preservar os dados brutos.

In [23]:
# Tratamento de exemplo: remover linhas completamente duplicadas
df_limpo = df.drop_duplicates()

print("Duplicatas completas antes:", df.duplicated().sum())
print("Duplicatas completas depois:", df_limpo.duplicated().sum())

df_limpo.to_csv("dados_alunos_limpos.csv", index=False, encoding="utf-8-sig")
print("Arquivo salvo: dados_alunos_limpos.csv")

Duplicatas completas antes: 3
Duplicatas completas depois: 0
Arquivo salvo: dados_alunos_limpos.csv

## 12. Resumo 

| Método | Para que serve |
|---|---|
| `duplicated()` | Identifica linhas duplicadas |
| `duplicated().sum()` | Conta duplicatas completas |
| `duplicated(keep=False)` | Marca todas as ocorrências duplicadas |
| `drop_duplicates()` | Remove linhas duplicadas |
| `subset=["coluna"]` | Compara apenas colunas escolhidas |
| `keep="first"` | Mantém a primeira ocorrência |
| `keep="last"` | Mantém a última ocorrência |
| `keep=False` | Remove todas as ocorrências dos grupos duplicados |
| `value_counts()` | Conta a frequência de valores em uma coluna |