# Tipos de Variaveis 

Objetivo:

- entender os tipos de variaveis 
- diferenciar variaveis numericas categoricas, binarias e temporais 
- exemplos praticos com pandas

In [8]:
! pip install pandas -q

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
# importando bibliotecas de analise de dados
import pandas as pd

In [10]:
dados = {
    "Nome": ["Alice", "Bob", "Charlie", "David"],
    "Idade": [25, 30, 35, 40],
    "Altura": [1.65, 1.80, 1.75, 1.70],
    "Curso": ["Engenharia", "Medicina", "Direito", "Ciência da Computação"],
    "Escolaridade": ["Medio", "Superior", "Superior", "Medio"],
    "Aprovado": [True, False, True, True],
    "Data_Matricula": pd.to_datetime(["2021-01-15", "2020-09-10", "2022-03-05", "2021-11-20"])
}

df = pd.DataFrame(dados)

In [11]:
df

,Nome,Idade,Altura,Curso,Escolaridade,Aprovado,Data_Matricula
0,Alice,25,1.65,Engenharia,Medio,True,2021-01-15
1,Bob,30,1.80,Medicina,Superior,False,2020-09-10
2,Charlie,35,1.75,Direito,Superior,True,2022-03-05
3,David,40,1.70,Ciência da Computação,Medio,True,2021-11-20

In [12]:
df.tail()

,Nome,Idade,Altura,Curso,Escolaridade,Aprovado,Data_Matricula
0,Alice,25,1.65,Engenharia,Medio,True,2021-01-15
1,Bob,30,1.80,Medicina,Superior,False,2020-09-10
2,Charlie,35,1.75,Direito,Superior,True,2022-03-05
3,David,40,1.70,Ciência da Computação,Medio,True,2021-11-20

In [ ]:
# convertendo a coluna 'Data_Matricula' para o tipo datetime

df['Data_Matricula'] = pd.to_datetime(df['Data_Matricula'])

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Nome            4 non-null      str
 1   Idade           4 non-null      int64
 2   Altura          4 non-null      float64
 3   Curso           4 non-null      str
 4   Escolaridade    4 non-null      str
 5   Aprovado        4 non-null      bool
 6   Data_Matricula  4 non-null      datetime64[us]
dtypes: bool(1), datetime64[us](1), float64(1), int64(1), str(3)
memory usage: 328.0 bytes

# Tipos de variaveis 
## Numericas 

- Discretas: assumem numeros inteiros
- Continuas: podem assumir numeros em qualquer intervalo de valor {ex: altura, peso}

In [15]:
print("Idade (variavel numerica Descreta)")
print(df['Idade'])
print("Altura (variavel numerica Continua)")
print(df['Altura'])

Idade (variavel numerica Descreta)
0    25
1    30
2    35
3    40
Name: Idade, dtype: int64
Altura (variavel numerica Continua)
0    1.65
1    1.80
2    1.75
3    1.70
Name: Altura, dtype: float64

# Variaveis Categoricas 

- Nominais: nao tem ordem ou hieraquia {ex: curso}
- Ordinais: possuem ordem natural, ordem logica ou hieraquica {ex: escolaridade}

In [16]:
print("Curso (variavel categorica nominal)")
print(df['Curso'])
print("Escolaridade (variavel categorica ordinal)")
print(df['Escolaridade'])

Curso (variavel categorica nominal)
0               Engenharia
1                 Medicina
2                  Direito
3    Ciência da Computação
Name: Curso, dtype: str
Escolaridade (variavel categorica ordinal)
0       Medio
1    Superior
2    Superior
3       Medio
Name: Escolaridade, dtype: str

# Variaveis Binarias

sao variaveis com apenas dois valores possiveis.

In [17]:
print("Aprovado (variavel categorica binaria)")
print(df['Aprovado'])

Aprovado (variavel categorica binaria)
0     True
1    False
2     True
3     True
Name: Aprovado, dtype: bool

# Variavel Temporais 

Representam tempo ou sequencia de eventos.

In [18]:
print("Data_Matricula (variavel de temporal)")
print(df['Data_Matricula'])

Data_Matricula (variavel de temporal)
0   2021-01-15
1   2020-09-10
2   2022-03-05
3   2021-11-20
Name: Data_Matricula, dtype: datetime64[us]